# Generated by Django 4.1.2 on 2022-12-17 03:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login', '0006_delete_denuncia'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Denuncia',
            fields=[
                ('folio', models.BigAutoField(primary_key=True, serialize=False)),
                ('tipo_de_daño', models.CharField(max_length=20)),
                ('estatus', models.CharField(default='En proceso', max_length=20)),
                ('fecha_hechos', models.DateField()),
                ('calle', models.CharField(blank=True, max_length=100, null=True)),
                ('número_exterior', models.CharField(blank=True, max_length=10, null=True)),
                ('número_interior', models.CharField(blank=True, max_length=10, null=True)),
                ('código_postal', models.CharField(blank=True, max_length=10, null=True)),
                ('colonia', models.CharField(blank=True, max_length=100, null=True)),
                ('localidad', models.CharField(blank=True, max_length=100, null=True)),
                ('del_mun', models.CharField(blank=True, max_length=100, null=True)),
                ('entidad_federativa', models.CharField(blank=True, max_length=100, null=True)),
                ('otros_datos_ubicación', models.CharField(blank=True, max_length=500, null=True)),
                ('relato_de_hechos', models.TextField()),
                ('denunciante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('víctima', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.víctima')),
            ],
        ),
    ]
