# Generated by Django 4.1.2 on 2022-12-28 21:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0018_víctima_entidad_federativa_and_more'),
        ('fud', '0002_remove_denuncia_entidad_federativa'),
    ]

    operations = [
        migrations.AddField(
            model_name='denuncia',
            name='entidad_federativa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entidad_federativa_denuncia', to='login.entidad_federativa'),
        ),
    ]
