# Generated by Django 4.1.2 on 2022-12-29 01:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
        ('fud', '0003_denuncia_entidad_federativa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='denuncia',
            name='entidad_federativa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entidad_federativa_denuncia', to='locations.entidad_federativa'),
        ),
    ]
