# Generated by Django 4.1.2 on 2022-11-04 21:19

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='TME_002_User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('nombres', models.CharField(blank=True, max_length=100, null=True)),
                ('primer_apellido', models.CharField(blank=True, max_length=100, null=True)),
                ('segundo_apellido', models.CharField(blank=True, max_length=100, null=True)),
                ('user_type', models.CharField(max_length=25)),
                ('is_profiled', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Servidor_Público',
            fields=[
                ('servidor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('institucion', models.CharField(max_length=100)),
                ('cargo', models.CharField(max_length=100)),
                ('tel_movil', models.CharField(blank=True, max_length=20, null=True)),
                ('tel_fijo', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Solicitante_Externo',
            fields=[
                ('solicitante', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('parentesco', models.CharField(max_length=100)),
                ('tel_movil', models.CharField(blank=True, max_length=20, null=True)),
                ('tel_fijo', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('otros_datos_contacto', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Víctima',
            fields=[
                ('víctima', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('tipo', models.CharField(max_length=10)),
                ('fecha_de_nacimiento', models.DateField()),
                ('sexo', models.CharField(max_length=10)),
                ('nacionalidad', models.CharField(blank=True, max_length=20, null=True)),
                ('curp', models.CharField(max_length=18)),
                ('pais_nacimiento', models.CharField(blank=True, max_length=50, null=True)),
                ('entidad_nacimiento', models.CharField(blank=True, max_length=50, null=True)),
                ('del_mun_nac', models.CharField(blank=True, max_length=50, null=True)),
                ('comunidad_nacimiento', models.CharField(blank=True, max_length=50, null=True)),
                ('estado_civil', models.CharField(max_length=20)),
                ('calle', models.CharField(max_length=100)),
                ('num_exterior', models.CharField(max_length=10)),
                ('num_interior', models.CharField(blank=True, max_length=10, null=True)),
                ('cp', models.CharField(max_length=10)),
                ('colonia', models.CharField(max_length=100)),
                ('localidad', models.CharField(blank=True, max_length=100, null=True)),
                ('del_mun', models.CharField(max_length=100)),
                ('entidad_federativa', models.CharField(max_length=100)),
                ('tel', models.CharField(blank=True, max_length=20, null=True)),
                ('email_victima', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
    ]
