# Generated by Django 4.1.2 on 2022-11-06 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_denuncia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='denuncia',
            name='estatus',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
