# Generated by Django 4.1.2 on 2022-11-06 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_alter_denuncia_estatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='denuncia',
            name='folio',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
