# Generated by Django 4.1.2 on 2022-11-07 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_alter_denuncia_folio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='denuncia',
            name='estatus',
            field=models.CharField(default='En proceso', max_length=20),
        ),
    ]
