# Generated by Django 4.1.2 on 2022-12-17 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_alter_denuncia_estatus'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Denuncia',
        ),
    ]
