# Generated by Django 4.1.2 on 2022-12-18 03:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_delete_denuncia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coordinador',
            fields=[
                ('coordinador', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
