# Generated by Django 4.1.2 on 2022-12-18 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0007_coordinador'),
    ]

    operations = [
        migrations.AddField(
            model_name='coordinador',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='coordinador',
            name='tel_fijo',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='coordinador',
            name='tel_movil',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
