# Generated by Django 4.1.2 on 2022-12-18 06:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0008_coordinador_email_coordinador_tel_fijo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trabajador_Social',
            fields=[
                ('trabajador_social', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('tel_movil', models.CharField(blank=True, max_length=20, null=True)),
                ('tel_fijo', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
    ]
