# Generated by Django 4.1.2 on 2022-12-25 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0009_trabajador_social'),
    ]

    operations = [
        migrations.CreateModel(
            name='Colonia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=150, null=True)),
                ('cp', models.CharField(blank=True, max_length=6, null=True)),
                ('delegación', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
