# Generated by Django 4.1.2 on 2022-12-28 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0013_colonia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entidad_Federativa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=50, null=True)),
                ('clave', models.CharField(blank=True, max_length=3, null=True)),
            ],
        ),
    ]
