# Generated by Django 4.1.2 on 2022-12-28 21:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0015_alter_víctima_entidad_nacimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='víctima',
            name='entidad_nacimiento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='login.entidad_federativa'),
        ),
    ]
