# Generated by Django 4.1.2 on 2022-12-28 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0016_alter_víctima_entidad_nacimiento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='víctima',
            name='entidad_federativa',
        ),
    ]
