# Generated by Django 4.1.2 on 2022-12-28 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0017_remove_víctima_entidad_federativa'),
    ]

    operations = [
        migrations.AddField(
            model_name='víctima',
            name='entidad_federativa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entidad_federativa', to='login.entidad_federativa'),
        ),
        migrations.AlterField(
            model_name='víctima',
            name='entidad_nacimiento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entidad_nacimiento', to='login.entidad_federativa'),
        ),
    ]
