# Generated by Django 4.1.2 on 2022-12-29 01:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fud', '0004_alter_denuncia_entidad_federativa'),
        ('locations', '0001_initial'),
        ('login', '0019_alcaldia'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Alcaldia',
        ),
        migrations.DeleteModel(
            name='Colonia',
        ),
        migrations.AlterField(
            model_name='víctima',
            name='entidad_federativa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entidad_federativa', to='locations.entidad_federativa'),
        ),
        migrations.AlterField(
            model_name='víctima',
            name='entidad_nacimiento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entidad_nacimiento', to='locations.entidad_federativa'),
        ),
        migrations.DeleteModel(
            name='Entidad_Federativa',
        ),
    ]
