# Generated by Django 4.1.2 on 2022-12-29 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0020_delete_alcaldia_delete_colonia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='víctima',
            name='colonia',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
