# Generated by Django 4.1.2 on 2022-12-29 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0021_alter_víctima_colonia'),
    ]

    operations = [
        migrations.RenameField(
            model_name='víctima',
            old_name='colonia',
            new_name='colonia_id',
        ),
    ]
