# Generated by Django 4.1.2 on 2022-12-30 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0022_rename_colonia_víctima_colonia_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='víctima',
            old_name='colonia_id',
            new_name='colonia',
        ),
    ]
