# Generated by Django 4.1.2 on 2022-12-30 21:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_colonia'),
        ('login', '0023_rename_colonia_id_víctima_colonia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='víctima',
            name='colonia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='locations.colonia'),
        ),
        migrations.AlterField(
            model_name='víctima',
            name='del_mun',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='locations.alcaldia'),
        ),
    ]
