# Generated by Django 4.1.2 on 2023-01-03 03:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0027_psicologo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('medico', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('tel_movil', models.CharField(blank=True, max_length=20, null=True)),
                ('tel_fijo', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
    ]
