# Generated by Django 4.1.2 on 2022-12-29 00:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alcaldia',
            fields=[
                ('nombre', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('latitud', models.FloatField(blank=True, null=True)),
                ('longitud', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Entidad_Federativa',
            fields=[
                ('nombre', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('clave', models.CharField(blank=True, max_length=3, null=True)),
            ],
        ),
        #migrations.CreateModel(
        #    name='Colonia',
        #    fields=[
        #        ('cp', models.CharField(max_length=6, primary_key=True, serialize=False)),
        #        ('colonia', models.CharField(blank=True, max_length=150, null=True)),
        #        ('alcaldia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='locations.alcaldia')),
        #        ('entidad_federativa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='locations.entidad_federativa')),
        #    ],
        #),
    ]
