# Generated by Django 4.1.2 on 2022-12-30 21:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_colonia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colonia',
            name='alcaldia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='locations.alcaldia'),
        ),
        migrations.AlterField(
            model_name='colonia',
            name='estado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='locations.entidad_federativa'),
        ),
    ]
